### PR TITLE
Handle surf vs imshow

### PR DESCRIPTION
**Pull request by thomasjm**
Based on our discussion on #41.

Seems to work, I also checked in the test notebook and added a surf example to it.

### CODE REVIEW

**Comment by blink1073** [comment]
This is great!  I am wary of adding that image though without knowing what license to associate with it, do you remind removing that part?  The random images get the point across.

**Comment by thomasjm** [comment]
Okay, done

**Comment by blink1073** [comment]
Thanks again!

**Comment by blink1073** [comment]
Released as `v0.18`

**Pull request merged**
