### PR TITLE
Add libglu1 to apt.txt, switch to JupyterLab for Binder

### PR DESCRIPTION
**Pull request by jtpio**
Follow-up #172.

[Binder](https://mybinder.org/v2/gh/jtpio/octave_kernel/libglu1?urlpath=/lab/tree/octave_kernel.ipynb)

### CODE REVIEW

**Comment by jtpio** [comment]
Waiting for the binder to build.

**Comment by jtpio** [comment]
Looking good now!

image

**Comment by jtpio** [comment]
cc @blink1073

**Comment by blink1073** [comment]
w00t!  Thanks again!

**Pull request merged**
