### PR TITLE
Switch to a data_files based install

### LINKED ISSUE #103: Can't register octave_kernel with Jupyter
Until https://github.com/Calysto/octave_kernel/commit/cab8ee253c61198c216ecd8bae178849b841678c I could use the old method to install the octave_kernel. Now I'm supposed to use the "metakernel standard install method," which doesn't seem to be well documented.

Bottom line: I have installed octave_kernel on a new machine, but can't get at it, as the second step, i.e. `python -m octave_kernel install` fails. A hint of how to use `--user` would also be helpful.
My old machines still can find the current octave_kernel, as everything was configured using the old install method.

I also need to fix the installation instructions for the MacPorts Portfile for py-octave_kernel, so others can install and use this.

### PR DESCRIPTION
**Pull request by blink1073**
Automatically install the kernel when installing the package.   Fixes #103 .

### CODE REVIEW

**Comment by dsblank** [comment]
Thanks for this! I'll use it as an example for the other kernels.

**Comment by dsblank** [comment]
BTW, what effect was the libedit change for?

**Comment by blink1073** [comment]
There is a conflicting dependency between it and the `octave` conda package, opened an issue [there](https://github.com/conda-forge/octave-feedstock/issues/6).

**Comment by blink1073** [comment]
I think I'd still like to have the advanced option of installing the kernel to a different spot if that makes more sense for the user, so they can remove our installed kernelspec and `python -m octave_kernel install --user`, so there's a bit of work left to do in this PR.

**Pull request merged**
