### PR TITLE
Add handling of input functions

### LINKED ISSUE #59: input() not supported
GNU Octave `input()` function appears not to be supported. Note that IPython kernels support python `input()` and `raw_input()`.

Other [terminal input functions](https://www.gnu.org/software/octave/doc/v4.2.0/Terminal-Input.html#Terminal-Input), `menu()`, `yes_or_no()`, and `kbhit()`, are also unsupported. But `input()` is probably the one that adds most value.

### PR DESCRIPTION
**Pull request by blink1073**
Fixes #59.  
Uses [add_input_event_hook](https://octave.sourceforge.io/octave/function/add_input_event_hook.html) to get a known stdin prompt, allowing `input`, `menu`, `yes_or_no`, and `keyboard` to work.  
Uses `@class` overrides for `kbhit`, `pause`, `sleep`, and `usleep`.  `kbhit` is a no-op with a printed warning and the others notify the user how long of a pause and to use the kernel interrupt to abort.

### CODE REVIEW

**Comment by blink1073** [comment]
For yes_or_no we can stuff a marker before the (yes or no).

**Comment by blink1073** [comment]
Released as `v0.20.0`.

**Comment by dsblank** [comment]
Excellent work, @blink1073 !

**Comment by blink1073** [comment]
That was a fun one, and something I had been trying to figure out for going on 4 years now in `oct2py`.  Thanks again, @DrXyzzy!

**Pull request merged**
