### PR TITLE
Snap plot fix

### PR DESCRIPTION
**Pull request by PhilFreeman**
Implemented fix for Issue #174. Updated README.rst to document how to use Octave-Snap.

### CODE REVIEW

**Comment by blink1073** [comment]
I'll merge and cut a release next time I'm on my computer.

**Comment by slel** [comment]
Typo: 
``` diff
- checing
+ checking
```

**Comment by blink1073** [comment]
Thanks @slel, fixed.

**Comment by blink1073** [comment]
Released as 0.32.0.

**Pull request merged**
